
export const ocrTextPage1 = `
Nº de Formulario: 685124-Fecha: 18/08/2025 - N° de Puesto: 367123
SOLICITUD DE DESIGNACIÓN DE PERSONAL DOCENTE, INTERINO O SUPLENTE
1. SOLICITUD DE PERSONAL DOCENTE
>
AREA: Área de Educación Superior
Página: 1/2
-
ESCUELA N°: 2
D.E./REG.: 6
REPARTICIÓN LOCAL : 35110000
ESTABLECIMIENTO: E.N.S. 2 - EN L.VIVAS M. ACOSTA
CÓDIGO DEL ESTABLECIMIENTO: 3511
CARGO A CUBRIR: MAESTRO DE MATERIAS ESPECIALES TECNOLOGÍAS, DISEÑO Y
PROGRAMACIÓN (EDUCACIÓN SUPERIOR)
MÓDULO : Sin módulo
PLAN DE ESTUDIOS:
ASIGNATURA:
HORAS CÁTEDRA A CUBRIR :
CANT. HS. CAT.: 0.00
Turno: TARDE
AÑO/DIV/COM/NIV: ///
GEF:
2. DATOS DE LA CAUSA DE LA SOLICITUD
DOCENTE TITULAR
APELLIDO Y NOMBRE:
CUIL:
TIPO DOC.:
Sexo:
FICHA N° :
DESDE :
HASTA:
MOTIVO DE LA COBERTURA: Creación Planta Orgánica Funcional
Nº DE EE. DE BAJA:
DOCENTE INTERINO
APELLIDO Y NOMBRE: FERNÁNDEZ ANDREA ISABEL
CUIL: 27329298790
TIPO DOC.: DN
MOTIVO DE LA COBERTURA: 70 Y-VIOLENCIA DE GENERO
N° DE EE. DE BAJA:
Sexo: F
FICHA N°: 503187
DESDE: 24/02/2025 HASTA: 31/07/2025
Firma y Sello de la Autoridad Competente
`;

export const ocrTextPage2 = `
N° de Formulario: 685124-Fecha: 18/08/2025-Nº de Puesto: 367123
SOLICITUD DE DESIGNACIÓN DE PERSONAL DOCENTE, INTERINO O SUPLENTE
3. DATOS DEL DOCENTE PROPUESTO
FECHA DE LA PROPUESTA: 13/08/2025 (Miércoles)
APELLIDO Y NOMBRE : Emanuel Alejandro Ferloni
CUIL: 20313438776
TIPO DOC.: DN
CARÁCTER DE LA DESIGNACIÓN: SUPLENTE
N° DE ORDEN DE MÉRITO: 5
PUNTAJE: 1.0000
Sexo: M
FICHA N° :
Rol:
Página: 2/2
LISTADO: Postulación ART66L
¿ACCEDE AL CARGO U HORAS CÁTEDRA POR HALLARSE EN DISPONIBILIDAD? : NO
Firma y Sello de la Autoridad Competente
¿SOLICITA LICENCIA POR ART. 67 O 71 PARA ACCEDER AL CARGO? NO
CADA 14/08/25
Lugar y Fecha
4. TOMA DE POSESIÓN
FECHA: 14/08/2025 (Jueves)
Ε.Ε. - 34142629 - 2025 - ESC200866
Firma del Docente
5. CESE
MOTIVO DE CESE :
FECHA DE CESE :
Firma y Selle-del Director
CAT
ENANUEL Pallai
Conformidad de Docente
(Firma y Aclaración)
Firma y Sello del Director
Conformidad de Docente
(Firma y Aclaración)
`;
